### ISSUE TITLE
with NGINX as reverse proxy

### ISSUE THREAD

**Issue by fzuletavgw** [bitnami/bitnami-docker-magento#104]
Hi,

I want to use nginx as a load balancer and it to handle SSL. 
`/` works great, but can't get `/admin` to work.

nginx default.conf:
```
upstream stream_backend {
    server magento_container:8080;
}
server {
    ...
    location / {
        proxy_pass                          http://stream_backend;
        proxy_set_header  Host              $host;
        proxy_set_header  Referer           $http_referer;
        proxy_set_header  X-Real-IP         $remote_addr;
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
        proxy_read_timeout                  900;
    }
}
```
on the docker-compose.yml I have for magento
```
  magento:
    container_name: magento_container
    image: 'bitnami/magento:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - MAGENTO_HOST=domain.com
      - MAGENTO_MODE=developer
      - ...
    ports:
      - 8080:80
      - 8443:443
```

^ That's working fine for accessing the "site" page at https://domain.com

but when I try to access the **https://domain.com/admin** I get a browser redirection to `http://domain.com/index.php/admin/admin/index/index/key/0e77ff1d6ba62ccb5ef7229a11de9e2fddf863fc5939e9a57ffeb8754e4d87c5/`
these are some logs from the `magento_container`:
```
192.168.144.4 - - [13/Mar/2019:11:18:45 +0000] "GET /admin HTTP/1.0" 302 -
192.168.144.4 - - [13/Mar/2019:11:18:53 +0000] "GET /index.php/admin/admin/index/index/key/0e77ff1d6ba62ccb5ef7229a11de9e2fddf863fc5939e9a57ffeb8754e4d87c5/ HTTP/1.0" 302 -
```

please help
