### ISSUE TITLE
Developing a Custom Theme

### ISSUE THREAD

**Issue by hhdivil** [bitnami/bitnami-docker-magento#106]
Hi, can you tell me the correct way to develop a theme with the docker container?  Normally I would add my theme into app/design/frontend/[Vendor]/[ThemeName] but that folder isn't available from /bitnami/magento/htdocs/app

I am having the same issue with adding modules by placing them in app/code as well which I assume is the same problem.

This is my docker-compose.yml:

````
version: '2'

services:
    mariadb:
        image: 'bitnami/mariadb:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=bn_magento
            - MARIADB_PASSWORD=your_password
            - MARIADB_DATABASE=bitnami_magento
        ports:
            - '3306'
        volumes:
            - './src/mariadb:/bitnami'
    magento:
        image: 'bitnami/magento:latest'
        environment:
            - MARIADB_HOST=mariadb
            - MARIADB_PORT_NUMBER=3306
            - MAGENTO_DATABASE_USER=bn_magento
            - MAGENTO_DATABASE_PASSWORD=your_password
            - MAGENTO_DATABASE_NAME=bitnami_magento
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './src/magento:/bitnami'
        depends_on:
            - mariadb
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        environment:
            PMA_HOST: mariadb
        ports:
            - '8002:80'
        links:
            - mariadb:mariadb
        depends_on:
            - mariadb
````

Thanks
