### ISSUE TITLE
Changing the port from 80/443 to 8080/8443 causes a 404 on the /admin url.

### ISSUE THREAD

**Issue by justinwatkins** [bitnami/bitnami-docker-magento#124]
I'm trying to use this as a base to develop and test modules.  It's such a faster setup.  The challenge on a windows machine, you just can't bind to port 80 and you can't bind to 80 or 443 without admin privileges.  It's easier to just bind to 8080/8443 because they are open and not privileged. 

I set the MAGENTO_HOST, EXTERNAL_HTTP_PORT_NUMBER, EXTERNAL_HTTPS_PORT_NUMBER, run a fresh build after clearing all saved volumes, containers, etc.

And if you set the port mappings to '8080:80' and '8443:443' the store front appears to be working.  The entries in the database for base and secure base are correct (http://localhost:8080 and https://localhost:8443).  However, I can not get the admin to work.  I believe whatever logic magento is doing internally to determine the url mapping looks at the port that it's responding to on Apache not the port that was used before the docker forward.  So in this scenario, if you rebind the ports to something other than what Apache is listening to you just get a 404 error for the admin.

This does not happen if you leave the default 80/443.

I looked through the code and it looks like someone started to add some APACHE_HTTP_PORT_NUMBER environment variables to rebind apache to different ports in the 2.3.3 version. That should solve this problem as long as I port forward docker '8080:8080' the same.  I tried setting these environment variables, but I don't think they are propagated through to the container.

Am I missing something?  It would be very elegant if this worked.

**Comment by burakcakirel** [comment]
Same issue here.

The following comment works for me:
https://github.com/bitnami/bitnami-docker-magento/issues/85#issuecomment-418826319

**Comment by justinwatkins** [comment]
Those values are set correctly.
https://localhost:8443/ works, I get all of the page and assets.
https://localhost:8443/admin - returns a 404.

If I change the port binding to '443:443' in docker, rerun the whole setup from cleaned volumes, it works.

How do you have it working?

From the database:
`# config_id, scope, scope_id, path, value, updated_at
'3', 'default', '0', 'web/unsecure/base_url', 'http://localhost:8080/', '2019-11-28 16:11:54'
'4', 'default', '0', 'web/secure/base_url', 'https://localhost:8443/', '2019-11-28 16:11:57'
`

**Comment by miguelaeh** [comment]
Hi @justinwatkins ,
If I understood it correctly you are facing issues with the admin URL, right?
Could you please check in the database the parameter `web/secureuse_in_adminhtml` ?

**Comment by justinwatkins** [comment]
Both 0 and 1 return a 404.  If it's set to 1, when I do http://localhost:8080/admin, it redirects to https://localhost:8443/index.php/admin, which also returns a 404 error.

**Comment by justinwatkins** [comment]
And maybe I wasn't clear enough, the /admin works on port 8080, just never on port 8443, no matter what I have set for secureuse_in_adminhtml.  I'd like this dev instance to run under SSL primarily because there are always issues if developers code in http and switch to https later.

**Comment by miguelaeh** [comment]
Hi @justinwatkins ,
How are you deploying the application? Are you using docker-compose? In that case can you please post the `docker-compose.yaml` file?
I would like to reproduce your exact environment.
In any case, I used this `docker-compose.yaml`:
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'bitnami/magento:2'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - EXTERNAL_HTTP_PORT_NUMBER=8080
      - EXTERNAL_HTTPS_PORT_NUMBER=8443
      - MAGENTO_HOST=172.17.0.10
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'bitnami/elasticsearch:6'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local
  magento_data:
    driver: local

```

And it worked, can you give it a try?
