### ISSUE TITLE
Magento 2.3.3 and PHP 7.3

### ISSUE THREAD

**Issue by phpdave11** [bitnami/bitnami-docker-magento#128]
Are there plans to upgrade the PHP version to 7.3, which is recommended by Magneto?  Currently, it's using 7.2.

**Comment by jotamartos** [comment]
Hi @phpdave11 ,

The added support for PHP 7.3 recently but they do support PHP 7.2 and 7.3 according to its website.

https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

Did you find any error when using the solution with PHP 7.2? 

Thanks

**Comment by jotamartos** [comment]
Sorry @phpdave11 ,

Didn't see this in its website

```
Magento recommends using PHP 7.3
```

We will open a task on our side to update the PHP version to 7.3. We will update this thread once we have more information

**Comment by phpdave11** [comment]
Thank you!  Security updates for PHP 7.2 will end on 30 Nov 2020, which was my main concern.

**Comment by jotamartos** [comment]
Hi @phpdave11,

You are right and we are aware of that date. But don't worry about that, we will move our applications from PHP 7.2 to PHP 7.3 before that date for sure. In this case, and as it's recommended by Magento, we are currently working on moving the solution to use PHP 7.3. The next Bitnami Magento version (7.3.4) will probably include that version. 

Thanks

**Comment by jotamartos** [comment]
Hi @phpdave11,

Magento is currently using PHP 7.3

https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/Dockerfile

Enjoy! :)

**Comment by mehrdadhosseinzadeh** [comment]
hi
i want to se magento bitnami docker image, but pull lasted version ( 4 )
i want to use magento 2.3.3 ( file and db structure )
i have non-docker project and we want to switch bitnami docker image and customization.

please help me

**Comment by rafariossaa** [comment]
Hi @mehrdadhosseinzadeh ,
  If you pull the image: `docker  pull docker.io/bitnami/magento:2.3.3` and you will get the latest image for magento 2.3.3.
  To use it in the `docker-compose.yaml`, that will bring up magento and the database, you will need to change the image line by:
```
...
    image: 'docker.io/bitnami/magento:2.3.3'
...
```
 Could you give it a try ?

**Comment by mehrdadhosseinzadeh** [comment]
@rafariossaa 

hi
thank you

i found two version of tag
bitnami/magento:2.3.3
and
magento:2.3.3-ol-7-r113


secound is up to date


i want to use this image on base and customise it in docker-compose.yml file

but have error in post_installation parametr

my docker-compose is :
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    container_name: 'magento_mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=magento
      - MARIADB_PASSWORD=magento
      - MARIADB_DATABASE=magento
      #- PHP_MEMORY_LIMIT=1G
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    container_name: 'magento_app'
    build: 
      context: ./Docker/app
#      args:
#        - GIT_USER=cicd
#        - GIT_TOKEN=_PVz8a_ov6yDasXyRpGy
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_PASSWORD=magento
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_USERNAME=rmi
      - MAGENTO_PASSWORD=magento2021
      - MAGENTO_EMAIL=info@rminno.com
      #- MAGENTO_HOST=127.0.0.1
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      #- NAMI_DEBUG=1
      #- MAGENTO_SKIP_REINDEX=no
      #- BITNAMI_APP_NAME="RMI Ecommerce"
      #- MARIADB_CLIENT_CREATE_DATABASE_PRIVILEGES="ALL"
      #- PHP_MEMORY_LIMIT="768M"
      #sudo sysctl -w vm.max_map_count=262144
      #sudo sysctl -w fs.file-max=65536
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./local/magento_data:/bitnami
#    command: '/opt/bitnamic/magento/htdocs/rebuild'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    container_name: 'magento_elasticsearch'
    environment:
      - ELASTICSEARCH_PLUGINS:analysis-icu,analysis-phonetic2
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    mem_limit: 1024m

volumes:
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local




is corect mariadb_host ? or mysql_host ? do you have complete docker-compose.yml file for magento 2.3.3. ?

**Comment by marcosbc** [comment]
Hi @mehrdadhosseinzadeh, if you use the below docker-compose it should work:

```yaml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'docker.io/bitnami/magento:2.3.3-debian-9-r64'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local
  magento_data:
    driver: local
```

That said, is there any reason you need 2.3.3 and 2.4 is not valid for you? Since 2.3.3 there have been a lot of changes, including Debian 9 -> 10 transition and the open sourcing of initialization scripts (in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) directory).
