### ISSUE TITLE
Please upgrade your database issue

### ISSUE THREAD

**Issue by be-codified** [bitnami/bitnami-docker-magento#139]
Hi,

I am using [bitnami/magento image](https://hub.docker.com/r/bitnami/magento/) and trying to set Magento show on __Debian virtual machine__. 

Here is my docker-compose.yml file

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    ports:
      - '3307:3306'
    volumes:
      - './data-db:/bitnami/mariadb'
  magento:
    image: 'bitnami/magento:2'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './data-magento:/bitnami'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'bitnami/elasticsearch:6'
    volumes:
      - 'elasticsearch-data:/bitnami/elasticsearch/data'
volumes:
  elasticsearch-data:
    driver: local
```
I am using /data-db and /data-magento as bind mount drives. 

Everything was working on my local machine, I even deleted things and run it again as a test.

So, here is what I did on the Debian:
- I cloned my repository
- Did `sudo docker-compose up`
- Dropped database, create new empty one
- Imported last db dump
- Run `docker-compose up` again

I am getting

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Amazon_Core schema: current version - 3.3.1, required version - 3.4.1
Amazon_Core data: current version - 3.3.1, required version - 3.4.1
Amazon_Login schema: current version - 3.3.1, required version - 3.4.1
...
```

I don't know why this is happening, any ideas? Thank you for the effort in advance.
