### ISSUE TITLE
Cannot add images to products

### ISSUE THREAD

**Issue by nl-it** [bitnami/bitnami-docker-magento#150]
**Description**

**Steps to reproduce the issue:**

1. run docker-compose up using the latest docker-compose.yml
2. Go to Catalogue -> Products
3. Create a new product
4. Save the product
5. Add images

**Describe the results you received:**

ATTENTION:
valkyrie_06_asset_09-altc6a502b9cf8b697fbc60ff00000f1b3f.jpg was not uploaded.
Unsupported image format. File: /opt/bitnami/php/tmp/phpBFKAKh

**Describe the results you expected:**

The image was added to the product

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
2.3.0.3 (45519)
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 20
  Running: 4
  Paused: 0
  Stopped: 16
 Images: 17
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.848GiB
 Name: docker-desktop
 ID: YUZR:6QQ2:HPH2:62NU:QZOW:FLU2:DWSI:X4XI:2MCQ:QADH:Z53X:EM3S
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 84
  Goroutines: 110
  System Time: 2020-06-17T15:12:07.631508035Z
  EventsListeners: 7
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.2-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'docker.io/bitnami/magento:2-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
      - elasticsearch
      - rabbitmq
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
    ports:
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
volumes:
  rabbitmq_data:
    driver: local
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local
  magento_data:
    driver: local

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
