### ISSUE TITLE
Error executing 'postInstallation': "size" argument must not be negative

### ISSUE THREAD

**Issue by BarisJKC** [bitnami/bitnami-docker-magento#159]
Hello,
os: ubuntu 20.04

I have the problem and logs from Magento service as per docker-compose.yml

> INFO  ==> Mounting certificates files from /certs...
nami    INFO  Initializing magento
Error executing 'postInstallation': "size" argument must not be negative

When the container runs w/o certs volume as below, it runs but I can not have my certs. When it runs with below volume, it stops and gives above problem in the log and does not start

>     volumes:
>      - "path/to/certs:/certs"

Any help is much appreciated.

Thank you 

#131

**Comment by rafariossaa** [comment]
Hi,
  This is what I did:
Create a directory to store the certs:
```
$ mkdir certs
$ cd certs
```
  Then I created a self signed cert with:
```
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt
```
  I modified the default docker-compose file to mount the certs directory:
```
...
     - ELASTICSEARCH_PORT_NUMBER=9200
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'magento_data:/bitnami'
      - ./certs:/certs
    depends_on:
      - mariadb
      - elasticsearch
...
```

  Could you try that ?
