### ISSUE TITLE
js and css not found when using custom ports

### ISSUE THREAD

**Issue by Fuseteam** [bitnami/bitnami-docker-magento#164]
i tried to the same as this repo https://github.com/bitnami/bitnami-docker-opencart/issues/66#issuecomment-677477266 to use magento2 on a custom port but i get the same issue as that one where the css and js files are not found due to it trying to read from port 443

**Comment by Fuseteam** [comment]
i have now also tried with EXTERNAL_HTTP_PORT and EXTERNAL_HTTPS_PORT environment variables same issue

**Comment by joancafom** [comment]
HI @Fuseteam 

Thanks for your issue! I was trying to replicate it, but did not face any problem. As you mentioned, this container does support the environment variables `EXTERNAL_HTTP_PORT ` and `EXTERNAL_HTTPS_PORT`, which are indeed intended designate the access ports from **outside the container.**

These are the steps that I have followed in order to set up Magento in a custom port accessible from the outside, let's say `8080` for HTTP and `8443` for HTTPS.

1. Specify the ports using the environment variables and map them correctly

```diff
$ cat docker-compose.yml

...
  magento:
    image: 'docker.io/bitnami/magento:2-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
++    - EXTERNAL_HTTP_PORT_NUMBER=8080
++    - EXTERNAL_HTTPS_PORT_NUMBER=8443
    ports:
--    - '80:80'
--    - '443:443'
++    - '8080:80'
++    - '8443:443'
...
```

2. It should be up and running 😁   Start the containers and head to http://localhost:8080 in this case

```console
$ docker-compose up
...
magento_1        | magento INFO
magento_1        | magento INFO  ########################################################################
magento_1        | magento INFO   Installation parameters for magento:
magento_1        | magento INFO     Username: user
magento_1        | magento INFO     Site URL: http://127.0.0.1:8080/
magento_1        | magento INFO     Admin URL: http://127.0.0.1:8080/admin
magento_1        | magento INFO   This installation requires no credentials.
magento_1        | magento INFO  ########################################################################
magento_1        | magento INFO
magento_1        | nami    INFO  magento successfully initialized
...
```

4. Additionally, I will check that an arbitrary image is reachable

```console
$ curl -L http://localhost:8080 | grep svg
    <img src="http://127.0.0.1:8080/pub/static/version1603178602/frontend/Magento/luma/en_US/images/logo.svg"

$ curl -L -I http://127.0.0.1:8080/pub/static/version1603178602/frontend/Magento/luma/en_US/images/logo.svg
HTTP/1.1 200 OK
Date: Tue, 20 Oct 2020 07:44:40 GMT
Server: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.23
Last-Modified: Tue, 20 Oct 2020 07:25:41 GMT
ETag: "eda-5b21523623d2d"
Accept-Ranges: bytes
Content-Length: 3802
X-Frame-Options: SAMEORIGIN
Cache-Control: public
Content-Type: image/svg+xml
```

Could you give it a try? Hope it helps, thanks!

**Comment by Fuseteam** [comment]
that's exactly what i tried, tho one difference is that i set MAGENTO_HOST=magento2.shop and MAGENTO_USE_SECURE_ADMIN=yes. could that be the issue?

**Comment by joancafom** [comment]
Hi @Fuseteam 

I have tried adding those env vars as well and it seems to work for me:

```yaml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'docker.io/bitnami/magento:2-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - EXTERNAL_HTTP_PORT_NUMBER=8080
      - EXTERNAL_HTTPS_PORT_NUMBER=8443
      - MAGENTO_HOST=magento2.shop
      - MAGENTO_USE_SECURE_ADMIN=yes
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local
  magento_data:
    driver: local
```

- Same test as before, but using the host instead:

```console
$ curl -L http://magento2.shop:8080 | grep svg
    <img src="http://magento2.shop:8080/pub/static/version1603265609/frontend/Magento/luma/en_US/images/logo.svg"

$ curl -L -I http://magento2.shop:8080/pub/static/version1603265609/frontend/Magento/luma/en_US/images/logo.svg
HTTP/1.1 200 OK
Date: Wed, 21 Oct 2020 07:39:29 GMT
Server: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.23
Last-Modified: Wed, 21 Oct 2020 07:36:38 GMT
ETag: "eda-5b22968674c05"
Accept-Ranges: bytes
Content-Length: 3802
X-Frame-Options: SAMEORIGIN
Cache-Control: public
Content-Type: image/svg+xml
```

- Additionally, the web seems to render properly

Could you provide me with the output of performing this simple test? Thanks!
