### ISSUE TITLE
Store search does not work

### ISSUE THREAD

**Issue by mofheu** [bitnami/bitnami-docker-magento#169]
**Store search does not work**

**Steps to reproduce the issue:**

1. Create Product from "CATALOG > Products > Add Product"
       - Enable Product: Yes
       - Attribute Set: Default
       - Product Name: test1
       - SKU: test1
       - Price: 100
       - Quantity: 300
       - Stock Status: In Stock
       - Weight: 1
       - Categories: Default Category, CategoryTest
            > New Category
                - Category Name: CategoryTest
                - Parent Category: Default Category
             > Create Category
        - Visibility: Catalog, Search
        > Save
2. Cache Management > Select All > Submit
3. In store search looks for test1 and returns nothing.

**Describe the results you received:**
Your search returned no results.

**Describe the results you expected:**

Found the product

**Additional information you deem important (e.g. issue happens only occasionally):**
The problem always happens.

**Version**

- Output of `docker version`:
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

- Output of `docker info`:

Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 3
  Paused: 0
  Stopped: 8
 Images: 12
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-54-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.6GiB
 Name: desktop
 ID: MKSV:HYBR:MHOR:NEDF:232N:JGTR:TWOT:SIAG:T3JC:XX7P:JAVZ:J4GS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: mofheu
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

- Output of `docker-compose version` (if applicable):

docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dani8art** [comment]
Hi @mofheu could you add a bit more context? how are you deploying the application? are you using `docker-compose`? or just docker commands?

**Comment by mofheu** [comment]
I make any scripts.

sudo ./install.sh

file content:
#!/bin/bash
echo "Installing..."
mkdir -m 777 magento_data
mkdir -m 777 mariadb_data
mkdir -m 777 elasticsearch_data
./start.sh


file content:
./start.sh
#!/bin/bash
echo "Starting..."
sudo sysctl -w vm.max_map_count=262144
sudo sysctl -w fs.file-max=65536
docker-compose up -d
echo "Done!"

**Comment by dani8art** [comment]
Could you also share your docker-compose.yaml, please?

**Comment by mofheu** [comment]
Of course. 
It is a small change of what is on the website https://hub.docker.com/r/bitnami/magento/

```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml> docker-compose.yml
$ docker-compose up -d
```

The difference is here: https://www.diffchecker.com/Qsl9Ub7M

Follows docker-compose.yml

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - './mariadb_data/:/bitnami/mariadb/data'
  magento:
    image: 'docker.io/bitnami/magento:2-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - MAGENTO_HOST=localhost
      - EXTERNAL_HTTP_PORT_NUMBER=8085
      - EXTERNAL_HTTPS_PORT_NUMBER=8086
    ports:
      - '8085:80'
      - '8086:443'
    volumes:
      - './magento_data/:/bitnami'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    volumes:
      - './elasticsearch_data/:/bitnami/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local
  magento_data:
    driver: local

```
