### ISSUE TITLE
Persist magento/app and composer.json

### ISSUE THREAD

**Issue by userz58** [bitnami/bitnami-docker-magento#181]
I can't persist the whole directory as docker works very slowly.

I would like to mount only the app directory and composer.json file, but I get errors

![bitnami-magento-1](https://user-images.githubusercontent.com/2612186/107762899-c2e32c80-6d3e-11eb-9f7c-6b5f3082adf6.jpg)
![bitnami-magento-2](https://user-images.githubusercontent.com/2612186/107762907-c5458680-6d3e-11eb-8c9b-8df4f43ad825.jpg)

-------------------

The same problem with mounting themes directories
![bitnami-magento-3](https://user-images.githubusercontent.com/2612186/107763043-ff168d00-6d3e-11eb-8061-270a96b47939.jpg)
![bitnami-magento-4](https://user-images.githubusercontent.com/2612186/107763051-00e05080-6d3f-11eb-879f-af656b82f38e.jpg)

**Comment by Mauraza** [comment]
Hi @userz58,

what are the permissions of the folders? if you check the [README.md](https://github.com/bitnami/bitnami-docker-magento#mount-host-directories-as-data-volumes-with-docker-compose) appears:

> NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.

**Comment by userz58** [comment]
Directory permissions set - all allowed.

Wthen i mount 'magento_data:/bitnami/magento' - all works (starts up and runs, but slowly)
I'm having trouble mounting internal directories /bitnami/magento/

**Comment by Mauraza** [comment]
Hi @userz58,

could you try with quotes and with the full path? 
I hope that helps you.

**Comment by userz58** [comment]
I already tried all possible mounting options on Windows and Mac. The result is the same.

**Comment by Mauraza** [comment]
Hi @userz58,

could you try the following steps:
if you have the folder `magento-data` , please remove and try to deploy the next the next docker-compose:

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: 'docker.io/bitnami/magento:2-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /magento_data:/bitnami/magento
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  elasticsearch_data:
    driver: local
```

with that the docker-compose it's running in windows 
![image](https://user-images.githubusercontent.com/17168510/108279076-4efcb600-717c-11eb-94e3-e15e642282b1.png)

**Comment by userz58** [comment]
![Снимок экрана 2021-02-18 в 18 26 07](https://user-images.githubusercontent.com/2612186/108379707-3f7e7b00-7217-11eb-9653-d6a6ced5c8d8.png)
i deleted magento_data directory

docker pull docker.io/bitnami/magento:2-debian-10
docker-compose up -d
![Снимок экрана 2021-02-18 в 18 28 01](https://user-images.githubusercontent.com/2612186/108380035-89676100-7217-11eb-894a-02528aacb889.png)


when i give path without quotes - docker throws error
    volumes:
      - /magento_data:/bitnami/magento

in this version - docker starts normally (will create new directory):
volumes:
      - ~/Sites/m2-test/magento_data/app:/bitnami/magento/app


remind the essence of the problem: I could always mount at the directory completely 'magento_data:/bitnami/magento'
but i can't mount:
**'app:/bitnami/magento/app'
'auth.json:/bitnami/magento/auth.json'**

**Comment by userz58** [comment]
![Снимок экрана 2021-02-18 в 18 48 00](https://user-images.githubusercontent.com/2612186/108382466-eb28ca80-7219-11eb-9b58-7206dd193519.png)
![Снимок экрана 2021-02-18 в 18 47 49](https://user-images.githubusercontent.com/2612186/108382483-eebc5180-7219-11eb-8022-6d06fb0b32a1.png)

**Comment by Mauraza** [comment]
Hi @userz58,

Sorry I missed the point in 'magento_data', I just added, that should be work.
```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: 'docker.io/bitnami/magento:2-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./magento_data:/bitnami/magento
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  elasticsearch_data:
    driver: local
```

About these paths: 
- './app:/bitnami/magento/app': The application needs differents files so they need more files like the error that appears.
You can check this appears in the README.md:

> For persistence you should mount a directory at the /bitnami/magento path. If the mounted directory is empty, it will be initialized on the first run. 


To change the files you want you and follow these steps:
- run `docker-compose up -d` (the I share with you) and wait that the initialization finishes,
- stops the containers 
- change the files you want, for example, `composer.json',
