### ISSUE TITLE
Can not run on apple m1

### ISSUE THREAD

**Issue by nancom** [bitnami/bitnami-docker-magento#182]
**Description**
 I try on my Apple MacBook Air M1

When download docker-compose file from this website . I try to use command docker-compose 
but not working Magento exit when  
```
magento          | magento 15:35:06.44
magento          | magento 15:35:06.46 Welcome to the Bitnami magento container
magento          | magento 15:35:06.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
magento          | magento 15:35:06.49 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
magento          | magento 15:35:06.50
magento          | magento 15:35:06.52 INFO  ==> ** Starting Magento setup **
magento          | magento 15:35:06.89 INFO  ==> Configuring PHP options
magento          | magento 15:35:07.02 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
magento          | magento 15:35:07.26 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
magento          | magento 15:35:07.47 INFO  ==> Ensuring Magento directories exist
magento          | magento 15:35:07.52 INFO  ==> Configuring permissions
magento          | magento 15:35:07.60 INFO  ==> Trying to connect to the database server
magento          | magento 15:35:07.69 INFO  ==> Trying to connect to Elasticsearch
magento          | magento 15:35:07.79 INFO  ==> Running Magento install script
magento exited with code 1
```
this is my compose file
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb'
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: 'bitnami/magento:2.4.1-debian-10-r96'
    container_name: magento
    platform: linux/amd64
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_USERNAME=admin
      - MAGENTO_PASSWORD=Passw0rd
      - MAGENTO_MODE=developer
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    links:
      - "mariadb:mariadb"
      - "elasticsearch:elasticsearch"    
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'bitnami/elasticsearch'
    container_name: elasticsearch
    platform: linux/amd64
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
```

Any suggestion ?
