### ISSUE TITLE
unable to connect to a database running on port other than 3306

### ISSUE THREAD

**Issue by eexplore** [bitnami/bitnami-docker-magento#185]
**Description**

Unfortunately, i'm not able to change the default port 3306 in mysql and magento2 containers. Everything is ok with 3306 but fails with other ports. Maybe, i'm wrong somewhere ?

**Steps to reproduce the issue:**

1. It works fine with this yml

```YAML
version: '3.1'

volumes:
  vol_mysql_magento: {}
  magento_data_01: {}
  elasticsearch_data_01: {}
  magento_data_02: {}
  elasticsearch_data_02: {}

networks:
  frontend:
    name: ntw_magento
    ipam:
      config:
        - subnet: 172.29.0.0/24

services:

  mysql_magento:
    image: mysql:5.7
    networks:
      frontend:
        ipv4_address: 172.29.0.2
    container_name: ctn_mysql_magento
    volumes:
      - vol_mysql_magento:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: magento_01
      MYSQL_USER: magento_dba
      MYSQL_PASSWORD: secret2
    entrypoint:
        sh -c "echo 'CREATE DATABASE IF NOT EXISTS magento_02;GRANT ALL PRIVILEGES ON magento_02.* TO '\''magento_dba'\''@'\''%'\'' IDENTIFIED BY '\''secret2'\'';flush privileges;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  phpmyadmin:
    depends_on:
      - mysql_magento
    image: phpmyadmin/phpmyadmin
    networks:
      frontend:
        ipv4_address: 172.29.0.3
    container_name: ctn_phpmyadmin_mg
    ports:
      - 4029:80
    restart: always
    environment:
      PMA_HOST: ctn_mysql_magento

  magento_01:
    depends_on:
      - mysql_magento
      - elasticsearch_01
    image: bitnami/magento
    networks:
      frontend:
        ipv4_address: 172.29.0.4
    container_name: ctn_magento_01
    volumes:
      - magento_data_01:/bitnami/magento
    ports:
      - 5029:8080
      - 5043:8443
    restart: always
    environment:
      MAGENTO_HOST: 192.168.1.222
      MAGENTO_EXTERNAL_HTTP_PORT_NUMBER: 5029
      MAGENTO_EXTERNAL_HTTPS_PORT_NUMBER: 5043
      MAGENTO_DATABASE_HOST: mysql_magento
      MAGENTO_DATABASE_PORT_NUMBER: 3306
      MAGENTO_DATABASE_NAME: magento_01
      MAGENTO_DATABASE_USER: magento_dba
      MAGENTO_DATABASE_PASSWORD: secret2
      ALLOW_EMPTY_PASSWORD: 'yes'
      MAGENTO_USERNAME: admin
      MAGENTO_PASSWORD: changeme1
      MAGENTO_SEARCH_ENGINE: elasticsearch7
      ELASTICSEARCH_HOST: elasticsearch_01
      ELASTICSEARCH_PORT_NUMBER: 9200
      PHP_POST_MAX_SIZE: 128M
      PHP_UPLOAD_MAX_FILESIZE: 128M

  magento_02:
    depends_on:
      - mysql_magento
      - elasticsearch_02
    image: bitnami/magento
    networks:
      frontend:
        ipv4_address: 172.29.0.5
    container_name: ctn_magento_02
    volumes:
      - magento_data_02:/bitnami/magento
    ports:
      - 6029:8080
      - 6043:8443
    restart: always
    environment:
      MAGENTO_HOST: 192.168.1.222
      MAGENTO_EXTERNAL_HTTP_PORT_NUMBER: 6029
      MAGENTO_EXTERNAL_HTTPS_PORT_NUMBER: 4043
      MAGENTO_DATABASE_HOST: mysql_magento
      MAGENTO_DATABASE_PORT_NUMBER: 3306
      MAGENTO_DATABASE_NAME: magento_02
      MAGENTO_DATABASE_USER: magento_dba
      MAGENTO_DATABASE_PASSWORD: secret2
      ALLOW_EMPTY_PASSWORD: 'yes'
      MAGENTO_USERNAME: admin
      MAGENTO_PASSWORD: changeme2
      MAGENTO_SEARCH_ENGINE: elasticsearch7
      ELASTICSEARCH_HOST: elasticsearch_02
      ELASTICSEARCH_PORT_NUMBER: 9201
      PHP_POST_MAX_SIZE: 128M
      PHP_UPLOAD_MAX_FILESIZE: 128M

  elasticsearch_01:
    image: docker.io/bitnami/elasticsearch:7-debian-10
    networks:
      frontend:
        ipv4_address: 172.29.0.6
    container_name: ctn_elasticsearch_01
    volumes:
      - elasticsearch_data_01:/bitnami/elasticsearch/data
    restart: always
    environment:
      ELASTICSEARCH_PORT_NUMBER: 9200

  elasticsearch_02:
    image: docker.io/bitnami/elasticsearch:7-debian-10
    networks:
      frontend:
        ipv4_address: 172.29.0.7
    container_name: ctn_elasticsearch_02
    volumes:
      - elasticsearch_data_02:/bitnami/elasticsearch/data
    restart: always
    environment:
      ELASTICSEARCH_PORT_NUMBER: 9201

```

2. Fail by replacing 3306 with 3307
```YAML
version: '3.1'

volumes:
  vol_mysql_magento: {}
  magento_data_01: {}
  elasticsearch_data_01: {}
  magento_data_02: {}
  elasticsearch_data_02: {}

networks:
  frontend:
    name: ntw_magento
    ipam:
      config:
        - subnet: 172.29.0.0/24

services:

  mysql_magento:
    image: mysql:5.7
    networks:
      frontend:
        ipv4_address: 172.29.0.2
    container_name: ctn_mysql_magento
    volumes:
      - vol_mysql_magento:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: magento_01
      MYSQL_USER: magento_dba
      MYSQL_PASSWORD: secret2
    entrypoint:
        sh -c "echo 'CREATE DATABASE IF NOT EXISTS magento_02;GRANT ALL PRIVILEGES ON magento_02.* TO '\''magento_dba'\''@'\''%'\'' IDENTIFIED BY '\''secret2'\'';flush privileges;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  phpmyadmin:
    depends_on:
      - mysql_magento
    image: phpmyadmin/phpmyadmin
    networks:
      frontend:
        ipv4_address: 172.29.0.3
    container_name: ctn_phpmyadmin_mg
    ports:
      - 4029:80
    restart: always
    environment:
      PMA_HOST: ctn_mysql_magento

  magento_01:
    depends_on:
      - mysql_magento
      - elasticsearch_01
    image: bitnami/magento
    networks:
      frontend:
        ipv4_address: 172.29.0.4
    container_name: ctn_magento_01
    volumes:
      - magento_data_01:/bitnami/magento
    ports:
      - 5029:8080
      - 5043:8443
    restart: always
    environment:
      MAGENTO_HOST: 192.168.1.222
      MAGENTO_EXTERNAL_HTTP_PORT_NUMBER: 5029
      MAGENTO_EXTERNAL_HTTPS_PORT_NUMBER: 5043
      MAGENTO_DATABASE_HOST: mysql_magento
      MAGENTO_DATABASE_PORT_NUMBER: 3307
      MAGENTO_DATABASE_NAME: magento_01
      MAGENTO_DATABASE_USER: magento_dba
      MAGENTO_DATABASE_PASSWORD: secret2
      ALLOW_EMPTY_PASSWORD: 'yes'
      MAGENTO_USERNAME: admin
      MAGENTO_PASSWORD: changeme1
      MAGENTO_SEARCH_ENGINE: elasticsearch7
      ELASTICSEARCH_HOST: elasticsearch_01
      ELASTICSEARCH_PORT_NUMBER: 9200
      PHP_POST_MAX_SIZE: 128M
      PHP_UPLOAD_MAX_FILESIZE: 128M

  magento_02:
    depends_on:
      - mysql_magento
      - elasticsearch_02
    image: bitnami/magento
    networks:
      frontend:
        ipv4_address: 172.29.0.5
    container_name: ctn_magento_02
    volumes:
      - magento_data_02:/bitnami/magento
    ports:
      - 6029:8080
      - 6043:8443
    restart: always
    environment:
      MAGENTO_HOST: 192.168.1.222
      MAGENTO_EXTERNAL_HTTP_PORT_NUMBER: 6029
      MAGENTO_EXTERNAL_HTTPS_PORT_NUMBER: 4043
      MAGENTO_DATABASE_HOST: mysql_magento
      MAGENTO_DATABASE_PORT_NUMBER: 3307
      MAGENTO_DATABASE_NAME: magento_02
      MAGENTO_DATABASE_USER: magento_dba
      MAGENTO_DATABASE_PASSWORD: secret2
      ALLOW_EMPTY_PASSWORD: 'yes'
      MAGENTO_USERNAME: admin
      MAGENTO_PASSWORD: changeme2
      MAGENTO_SEARCH_ENGINE: elasticsearch7
      ELASTICSEARCH_HOST: elasticsearch_02
      ELASTICSEARCH_PORT_NUMBER: 9201
      PHP_POST_MAX_SIZE: 128M
      PHP_UPLOAD_MAX_FILESIZE: 128M

  elasticsearch_01:
    image: docker.io/bitnami/elasticsearch:7-debian-10
    networks:
      frontend:
        ipv4_address: 172.29.0.6
    container_name: ctn_elasticsearch_01
    volumes:
      - elasticsearch_data_01:/bitnami/elasticsearch/data
    restart: always
    environment:
      ELASTICSEARCH_PORT_NUMBER: 9200

  elasticsearch_02:
    image: docker.io/bitnami/elasticsearch:7-debian-10
    networks:
      frontend:
        ipv4_address: 172.29.0.7
    container_name: ctn_elasticsearch_02
    volumes:
      - elasticsearch_data_02:/bitnami/elasticsearch/data
    restart: always
    environment:
      ELASTICSEARCH_PORT_NUMBER: 9201

```

**Describe the results you received:**

Details of the logs output

```
magento 13:20:53.65 ,
magento 13:20:53.66 Welcome to the Bitnami magento container,
magento 13:20:53.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento,
magento 13:20:53.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues,
magento 13:20:53.66 ,
magento 13:20:53.66 INFO  ==> ** Starting Magento setup **,
magento 13:20:53.76 INFO  ==> Configuring PHP options,
magento 13:20:53.76 INFO  ==> Setting PHP post_max_size option,
magento 13:20:53.77 INFO  ==> Setting PHP upload_max_filesize option,
magento 13:20:53.82 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars,
magento 13:20:53.89 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.,
magento 13:20:53.96 INFO  ==> Ensuring Magento directories exist,
magento 13:20:53.97 INFO  ==> Configuring permissions,
magento 13:20:53.98 INFO  ==> Trying to connect to the database server,
magento 13:21:54.39 ERROR ==> Could not connect to the database,
magento 13:21:55.59 ,
magento 13:21:55.59 Welcome to the Bitnami magento container,
magento 13:21:55.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento,
magento 13:21:55.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues,
magento 13:21:55.60 ,
magento 13:21:55.60 INFO  ==> ** Starting Magento setup **,
magento 13:21:55.64 INFO  ==> Configuring PHP options,
magento 13:21:55.65 INFO  ==> Setting PHP post_max_size option,
magento 13:21:55.65 INFO  ==> Setting PHP upload_max_filesize option,
magento 13:21:55.67 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars,
magento 13:21:55.70 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.,
magento 13:21:55.72 INFO  ==> Ensuring Magento directories exist,
magento 13:21:55.73 INFO  ==> Configuring permissions,
magento 13:21:55.73 INFO  ==> Trying to connect to the database server,
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:32 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-43-generic
 Operating System: Ubuntu 20.10
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 27.19GiB
 Name: ubuntu
 ID: QONJ:5KXG:DNHR:MKAM:PR3H:IRBX:ICIN:I6EG:ZAO3:VR45:KTK2:NL4E
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: eexplore
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.6
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Windows 10 Hyper-V host, Ubuntu Server 20.04 guest
