### ISSUE TITLE
Can't configure magento docker with elastich search cloud

### ISSUE THREAD

**Issue by kyurkchyan** [bitnami/bitnami-docker-magento#201]
**Description**

We are trying to deploy Magento through the docker image. To make it production-grade and manageable, we strive to use managed cloud services as much as possible. One of the steps is moving away from an elastic search that's deployed within the docker image to [ElasticSearch Cloud](https://www.elastic.co/cloud/). Here's the docker-compose file that we use

```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_ELASTICSEARCH_ENABLE_AUTH=yes
      - ELASTICSEARCH_HOST=*******.es.westeurope.azure.elastic-cloud.com
      - ELASTICSEARCH_PORT_NUMBER=9243
      - MAGENTO_ELASTICSEARCH_USER=elastic
      - MAGENTO_ELASTICSEARCH_PASSWORD=********
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
```

We are using ElasticSearch cloud instance deploy in the west-Europe region of Azure. Here are the log messages that we see at the end of the docker-compose process

```
magento_1  | magento 06:20:57.68 INFO  ==> Trying to connect to Elasticsearch
magento_1  | magento 06:20:57.88 INFO  ==> Running Magento install script
magento_magento_1 exited with code 1
```

It seems that the script is able to connect to the elastic search cloud, however, for some reason it fails. Is there any other place that we could look for to get more details about what's going wrong? 

**Steps to reproduce the issue:**

1. Deploy an ElasticSearch Cloud instance
2. You the above docker-compose file to deploy local docker images by replacing URLs and Passwords

**Describe the results you received:**

Instead of successful Elastic Search Cloud installation the script fails with the above mentioned error

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.771GiB
 Name: docker-desktop
 ID: QRP3:6WXW:3DA5:RPAS:N3GP:K2VV:2WYP:ZPYQ:BIBG:PZQJ:FUO7:HUTN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
- Windows details
```
Edition	Windows 10 Pro
Version	21H1
Installed on	‎5/‎26/‎2021
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0
```

**Comment by Mauraza** [comment]
Hi @kyurkchyan,

Could you add `BITNAMI_DEBUG=true`in the docker-compose?
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - BITNAMI_DEBUG=true
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_ELASTICSEARCH_ENABLE_AUTH=yes
      - ELASTICSEARCH_HOST=*******.es.westeurope.azure.elastic-cloud.com
      - ELASTICSEARCH_PORT_NUMBER=9243
      - MAGENTO_ELASTICSEARCH_USER=elastic
      - MAGENTO_ELASTICSEARCH_PASSWORD=********
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local

```
