### ISSUE TITLE
Setup SSL Cert upon inital install

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/bitnami-docker-magento#202]
**Description**

I use the [Helm chart to install Magento](https://bitnami.com/stack/magento/helm) on a Kubernetes cluster setup by [Docker Desktop for Mac](https://www.docker.com/products/docker-desktop).

Is it possible to setup SSL Cert upon the initial install of Magento (e.g. using `magentoHost`)?

**Steps to reproduce the issue:**

1. Create a `values.yaml`
```YAML
image:
  debug: true
magentoHost: magento.localtest.me
magentoPassword: Bitnami1
magentoAdminUri: admin
magentoUseHttps: true
magentoUseSecureAdmin: true
mariadb:
  auth:
    rootPassword: Covid-19
    password: Hello2021
elasticsearch:
  extraConfig:
    indices.breaker.total.use_real_memory: false
```
2. Install using `helm`:
```Shell
helm install demo bitnami/magento -n demo --create-namespace -f ./values.yaml
```
3. View the logs of the `magento` pod

**Describe the results you received:**
The logs show the following warning:
```
[Thu Jul 22 11:27:20.955627 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
```

**Describe the results you expected:**

Apache would not complain as it has the correct cert generated.

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 35
  Running: 30
  Paused: 0
  Stopped: 5
 Images: 20
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.776GiB
 Name: docker-desktop
 ID: IHAP:6HMN:SPT3:NMTJ:NRRP:ML2P:KHMV:IXZT:7MNI:G6O7:UU2M:2NIW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `kubectl version --short`:

```
Client Version: v1.21.2
Server Version: v1.21.2
```

- Output of `helm version --short`:

```
v3.6.3+gd506314
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
  Could you take  a look to [this](https://github.com/bitnami/charts/tree/master/bitnami/magento#user-content-tls-secrets) ? Maybe that helps.

**Comment by hussam-qasem** [comment]
Thank you Rafael @rafariossaa. 

I have a self-signed SSL Cert for the `magentoHost`. However, I do not quite understand how to instruct the Helm chart to use my `.crt` and `.key` files. I followed the instructions below to create a [kubernetes tls secret](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) named `magento.local-tls`:

https://github.com/bitnami/charts/tree/master/bitnami/magento#tls-secrets

and did the following:

```Shell
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=*.localtest.me"

kubectl create ns demo
kubectl -n demo create secret tls magento.local-tls --cert=tls.crt --key=tls.key
```

**Comment by rafariossaa** [comment]
Now, you should enable ingress and use `ingress.secrets` to indicate secret you have just created.

**Comment by hussam-qasem** [comment]
Thanks Rafel @rafariossaa for your response. Unfortunately, I seem to be having mixed results, and I can seem to get Magento to work with SSL. This is my `values.yaml` file so far:
```YAML
image:
  debug: true
magentoHost: magento.localtest.me
magentoPassword: Bitnami1
magentoAdminUri: admin
# magentoUseHttps: true
# magentoUseSecureAdmin: true
persistence:
  enabled: false
mariadb:
  auth:
    rootPassword: Covid-19
    password: Hello2021
  primary:
    persistence:
      enabled: false
elasticsearch:
  extraConfig:
    indices.breaker.total.use_real_memory: false
  master:
    persistence:
      enabled: false
  data:
    persistence:
      enabled: false
ingress:
  enabled: true
  hostname: magento.local
  path: /
  #tls: true
  extraTls:
  - hosts:
      - magento.local
    secretName: magento.local-tls
  # secrets:
  #  - name: magento.localtest.me-tls
  #    key: <base64 -w 0 tls.key>
  #    certificate: <base64 -w 0 tls.crt>
```

For the SSL cert, I do the following:
```Shell
KEY_FILE=tls.key
CERT_FILE=tls.crt
HOST=magento.local
CERT_NAME=${HOST}-tls
NAMESPACE=demo
rm ${KEY_FILE} ${CERT_FILE}
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout ${KEY_FILE} -out ${CERT_FILE} -subj "/CN=${HOST}/O=${HOST}"
kubectl create namespace ${NAMESPACE}
kubectl create secret tls ${CERT_NAME} --key ${KEY_FILE} --cert ${CERT_FILE} --namespace ${NAMESPACE}
```
And finally, I install using:
```Shell
helm install demo bitnami/magento -n ${NAMESPACE} -f ./values.yaml
```
