### ISSUE TITLE
SampleData installation fails during setup:upgrade with non-root user: 1001

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/bitnami-docker-magento#204]
**Description**

Unable to install Magento2 Sample Data with [non-root `user: "1001"`](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80)

**Steps to reproduce the issue:**
1. Follow the instructions on the [bitnami-docker-magento GitHub](https://github.com/bitnami/bitnami-docker-magento) page:

```shell
mkdir m2
cd m2
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml
```
2. Modify `docker-compose.yml` to run as non-root:
```YAML
  magento:
    image: docker.io/bitnami/magento:2
    user: "1001"
```
3. Start containers
```shell
docker-compose up -d
```
4. Wait until all services are running. Confirm by accessing `http://localhost`
5. Exec into container:
```
docker exec -it m2_magento_1 bash
```
6. Install Magento2 Sample Data using: ([Authentication required for `repo.magento.com`](https://account.magento.com/customer/identity/manager/
))
```Shell
cd /bitnami/magento
php -d memory_limit=-1 bin/magento -vvv sampledata:deploy
php -d memory_limit=-1 bin/magento -vvv setup:upgrade
```

**Describe the results you received:**

Process exits with error code(1):
```
Module 'Magento_DownloadableSampleData':
Enabling caches:
Current status:
layout: 1
block_html: 1
full_page: 1

Unable to apply data patch Magento\DownloadableSampleData\Setup\Patch\Data\InstallDownloadableSampleData for module Magento_DownloadableSampleData. Original exception message: Rolled back transaction has not been completed correctly.
```
<img width="737" alt="Screen Shot 2021-07-28 at 3 56 16 PM" src="https://user-images.githubusercontent.com/68053227/127325987-93bf93e7-0f84-495b-92bf-2720579bb30c.png">

**Describe the results you expected:**

`bin/magento setup:upgrade` Process to complete successfully.

**Additional information you deem important:**

Even when running the container as `root`, I was unable to deploy the Sample Data successfully. I did the following:
```shell
cd /bitnami/magento
php -d memory_limit=-1 bin/magento -vvv sampledata:deploy
php -d memory_limit=-1 bin/magento -vvv setup:upgrade
php -d memory_limit=-1 bin/magento -vvv setup:di:compile
php -d memory_limit=-1 bin/magento -vvv setup:static-content:deploy -f
```

Everything completes successfully; however, when accessing the website it returns `HTTP/1.1 200 OK` with the following message:
```console
An error has happened during application run. See exception log for details.
```

Inspecting `/bitnami/magento/var/log/debug.log` on the container, yields the following:
```log
[2021-07-28 19:47:54] main.CRITICAL: Error: Class 'Magento\ThemeSampleData\Plugin\View\Page\Config' not found in /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#1 /bitnami/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create()
#2 /bitnami/magento/vendor/magento/framework/Interception/PluginList/PluginList.php(174): Magento\Framework\ObjectManager\ObjectManager->get()
#3 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(144): Magento\Framework\Interception\PluginList\PluginList->getPlugin()
#4 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Page\Config\Interceptor->Magento\Framework\Interception\{closure}()
#5 /bitnami/magento/generated/code/Magento/Framework/View/Page/Config/Interceptor.php(23): Magento\Framework\View\Page\Config\Interceptor->___callPlugins()
#6 /bitnami/magento/vendor/magento/framework/View/Page/Config/Renderer.php(138): Magento\Framework\View\Page\Config\Interceptor->getIncludes()
#7 /bitnami/magento/vendor/magento/framework/View/Result/Page.php(250): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#8 /bitnami/magento/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#9 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#10 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#11 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#12 /bitnami/magento/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#13 /bitnami/magento/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#14 /bitnami/magento/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
#15 /bitnami/magento/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#16 {main} [] []
```

**Version**

- Output of `docker version`:

```
Client:
 Version:           20.10.7

Server: Docker Engine - Community
  Version:          20.10.7
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
```

**Comment by alvneiayu** [comment]
hi @hussam-qasem

I think that you are having problem with the Magento volume permissions (magento_data). Are you changing the docker-compose to use one in local? If yes, could you test setting up full permissions (chmod 777) just to verify that the problem comes from there.

Moreover, Magento is running with root user because Magento needs cron and you need root permissions to run it. I think that you will face more problems like the cron one.

Thanks a lot

Álvaro

**Comment by hussam-qasem** [comment]
Thank you Álvaro @alvneiayu for your response. In the example above, I'm using a fresh install every time, without modifying `docker-compose.yml` (with the exception of adding `user: "1001"`).

I confirmed there's nothing that's not owned by non-1001 in the `/bitnami/magento` folder:
```
find /bitnami/magento ! -user 1001
```

I'm certain you'll get the same behavior if you download [`docker-compose.yml`](https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml) and add `user: "1001"`

Though I also don't understand why I can't install the SampleData even with the container running as `root`

---

Regarding `cron`, what's the recommendation of running `cron` as non-root then? Thanks!

**Comment by alvneiayu** [comment]
hi @hussam-qasem 

You are running the container with the user 1001. But the configuration in the container is using the root user. This is for security, no ones can change anything in your container unless you are the root in the container.

Could you share with me the steps that you are following to install SampleData? I am not expert in this container but I will try to reproduce your problem in my local.

And about the recommendation to run cron as non-root, to be honest. I am not sure. Maybe you can take a look and port the cron task to your specific user and verify that they are running properly (but I think that you are going to find permission problems again).

Thanks a lot

Álvaro

**Comment by hussam-qasem** [comment]
Thanks @alvneiayu Álvaro for your response. I like the idea of running as non-root, but I'm under the impression that everything (Magento-wise) should function without a problem, or at least that's the premise.

To replicate the problem, please do the following:
1. Download `docker-compose.yml` into a directory, e.g. `m2`:
```Shell
mkdir m2
cd m2
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml
```
2. Modify `docker-compose.yml` to add the line: `user: "1001"`. The file now looks like:
```Yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:2
    user: "1001"
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
```
3. Create and start containers:
```Shell
 docker-compose up -d
```
4. Wait until containers and services are running. You may inspect the logs using: `docker logs -f m2_magento_1`, the following shall be printed:
```logs
magento 09:45:58.94 INFO  ==> ** Starting Apache **
[Mon Aug 02 09:45:59.079312 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 02 09:45:59.079754 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 02 09:45:59.118266 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 02 09:45:59.119175 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 02 09:45:59.173841 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.48 (Unix) OpenSSL/1.1.1d PHP/7.4.21 configured -- resuming normal operations
[Mon Aug 02 09:45:59.173923 2021] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```
5. Exec into the magento container:
```Shell
docker exec -it m2_magento_1 bash
```
6.  Your prompt will look like: `I have no name!@04375ed6389d:/$`. Type the following:
```Shell
cd /bitnami/magento
php -d memory_limit=-1 bin/magento -vvv sampledata:deploy
php -d memory_limit=-1 bin/magento -vvv setup:upgrade
```
7. The last command will fail with the following error:
```
Unable to apply data patch Magento\DownloadableSampleData\Setup\Patch\Data\InstallDownloadableSampleData for module Magento_DownloadableSampleData. Original exception message: Rolled back transaction has not been completed correctly.
```
8. Inspecting `/bitnami/magento/var/log/debug.log` yields:
```
[2021-08-02 10:04:28] main.ERROR: Sample Data error: The path "/opt/bitnami/php/tmp/." is not writable. [] []
```

So, I believe the original bitnami/magento container should have:
```
chmod 1777 /opt/bitnami/php/tmp
```
