### ISSUE TITLE
/bitnami/magento folder is empty when deployed in Kubernetes

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/bitnami-docker-magento#229]
**Description**

When deploying in Kubernetes (`persistence` disabled), the `/bitnami/magento` folder is empty in an extended image with the `/bitnami/magento` folder populated.

**Steps to reproduce the issue:**

1. Create a sample directory:
```Shell
mkdir -p magento/foo
touch magento/foo/bar.txt
```
2. Extend the base image. Create a `Dockerfile`:
```Dockerfile
FROM docker.io/bitnami/magento:2.4.3
USER 0
COPY --chown=1001:0 magento /bitnami/magento
RUN chown 1001:0 /bitnami/magento && chmod 2775 /bitnami/magento
USER 1001
```
3. Build the image:
```Shell
docker build -t localhost:5000/my-magento:2.4.3 .
docker push localhost:5000/my-magento:2.4.3
```
4. Create a sample deployment [`values.yml`](https://github.com/bitnami/charts/blob/master/bitnami/magento/values.yaml):
```YAML
image:
  registry: localhost:5000
  repository: my-magento
  tag: 2.4.3
  debug: true
magentoHost: magento.localtest.me
magentoPassword: Bitnami1
magentoAdminUri: admin
persistence:
  enabled: false
elasticsearch:
  master:
    persistence:
      enabled: false
  data:
    persistence:
      enabled: false
mariadb:
  auth:
    rootPassword: Covid-19
    password: Hello2021
  primary:
    persistence:
      enabled: false
```
5. Deploy using Kubernetes
```Shell
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm -n demo install shop bitnami/magento --create-namespace -f ./values.yaml
```

**Describe the results you received:**

Exec into the container, (e.g. `kubectl -n demo exec -it shop-magento-* -- bash`):
```Shell
cd /bitnami/magento
ls -l
```
The directory is empty!

**Describe the results you expected:**

The `foo` directory and `foo/bar.txt` file should be present. The Magento logs should say:
```
Restoring persisted Magento installation
```

**Additional information you deem important:**

My goal is to save precious startup time by copying (baking) an existing Magento installation into the `/bitnami/magento` directory. I'm just surprised to see the folder disappears, and I can't tell what I'm doing wrong.
