### ISSUE TITLE
Issue connecting to AWS Aurora RDS instance using bitnami/docker-magento compose file

### ISSUE THREAD

**Issue by kd-labs** [bitnami/bitnami-docker-magento#230]
**Not able to connect to AWS Aurora instance**

I am trying to use the bitnami magento image to connect aws aurora instance but I'm not able to do even after overriding the below env vars : 

      - MAGENTO_DATABASE_HOST=<public-name>.rds.amazonaws.com
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=<some-user>
      - MAGENTO_DATABASE_PASSWORD=<some-password>
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MYSQL_CLIENT_FLAVOR=mysql
      - MYSQL_CLIENT_DATABASE_HOST=<public-name>.rds.amazonaws.com
      - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_magento
      - MYSQL_CLIENT_DATABASE_ROOT_USER=<root-user>
      - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=<root-password>

**Steps to reproduce the issue:**

1. docker-compose up -d
2. docker logs [container id of magento_magento]

**Describe the results you received:**

Container running magento first uses mysql client to connect to aws rds instance to create schema which it is able to do but then magento is not able to connect to the rds instance and closes.

**Describe the results you expected:**

I expected that magento instance would be able to connect to the rds instance after overriding the db connection env vars.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 20.10.10, build b485636
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by kd-labs** [comment]
Below is the compose file I'm using. 

**Observations** - mysql client launching in php container running magento is able to create the schema 'bitnami_magento' in aws db instance...but magento web app, which I presume runs after mysql client has created the schema in remote db, is not able to connect to the remote aws db server.

```yaml
version: '2'
services:
  # mariadb:
  #   image: docker.io/bitnami/mariadb:10.3
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MARIADB_USER=bn_magento
  #     - MARIADB_DATABASE=bitnami_magento
  #   volumes:
  #     - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_MODE=developer
      - MYSQL_CLIENT_FLAVOR=mysql
      - MYSQL_CLIENT_DATABASE_HOST=<public-name>.rds.amazonaws.com
      - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_magento
      - MYSQL_CLIENT_DATABASE_ROOT_USER=<root-user>
      - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=<root-password>
      - MYSQL_CLIENT_CREATE_DATABASE_USER=<some-user>
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=<public-name>.rds.amazonaws.com
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=<some-user>
      - MAGENTO_DATABASE_PASSWORD=<some-password>
      - MAGENTO_DATABASE_NAME=bitnami_magento
      # - MARIADB_HOST=mariadb
      # - MARIADB_PORT_NUMBER=3306
      # - MARIADB_ROOT_PASSWORD=password
      # - MARIADB_ROOT_USER=admin
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  # mariadb_data:
  #   driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
```

**Comment by alemorcuq** [comment]
Could you share your logs with the environment variable `BITNAMI_DEBUG=true` set?

**Comment by kd-labs** [comment]
> Could you share your logs with the environment variable `BITNAMI_DEBUG=true` set?

```sh
magento 12:23:25.67
magento 12:23:25.67 Welcome to the Bitnami magento container
magento 12:23:25.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
magento 12:23:25.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
magento 12:23:25.67
magento 12:23:25.68 INFO  ==> ** Starting Magento setup **
magento 12:23:25.69 DEBUG ==> Validating settings in APACHE_* environment variables
realpath: /bitnami/apache/conf: No such file or directory
magento 12:23:25.73 INFO  ==> Configuring PHP options
magento 12:23:25.74 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
magento 12:23:25.75 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
magento 12:23:25.75 INFO  ==> Trying to connect to the database server
magento 12:23:25.75 DEBUG ==> Executing SQL command:
SELECT 1
1
magento 12:23:27.04 INFO  ==> Creating database user dev
magento 12:23:27.04 DEBUG ==> creating database user \'dev\'
magento 12:23:27.05 DEBUG ==> Executing SQL command:
create user if not exists 'dev'@'%' identified by "password";
magento 12:23:28.36 DEBUG ==> Removing all other hosts for the user
magento 12:23:28.36 DEBUG ==> Executing SQL command:
select Host from user where User='dev' and Host!='%';
magento 12:23:29.84 INFO  ==> Creating database bitnami_magento
magento 12:23:29.84 DEBUG ==> Creating database bitnami_magento
magento 12:23:29.85 DEBUG ==> Executing SQL command:
create database if not exists `bitnami_magento` ;
magento 12:23:31.45 DEBUG ==> Providing privileges to username dev on database bitnami_magento
magento 12:23:31.45 DEBUG ==> Executing SQL command:
grant ALL on `bitnami_magento`.* to 'dev'@'%';
magento 12:23:33.04 DEBUG ==> Validating settings in MAGENTO_* environment variables...
magento 12:23:33.05 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
magento 12:23:33.10 INFO  ==> Restoring persisted Magento installation
magento 12:23:40.02 INFO  ==> Trying to connect to the database server
magento 12:23:40.02 DEBUG ==> Getting configuration path '/db/connection/default/dbname' from Magento configuration
magento 12:23:40.04 DEBUG ==> Getting configuration path '/db/connection/default/username' from Magento configuration
magento 12:23:40.06 DEBUG ==> Getting configuration path '/db/connection/default/password' from Magento configuration
magento 12:23:40.08 DEBUG ==> Getting configuration path '/db/connection/default/host' from Magento configuration
magento 12:23:40.10 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:23:45.17 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:23:50.25 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:23:55.33 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:00.40 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:05.47 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:10.54 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:15.61 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:20.69 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:25.76 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:30.83 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:35.91 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:40.98 ERROR ==> Could not connect to the database
```


The magento service section in compose file is : 

``` yaml
version: '2'
services:
  magento:
    image: docker.io/bitnami/magento
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      # MYSQL CLIENT ENV PROPS
      - MYSQL_CLIENT_FLAVOR=mysql
      - MYSQL_CLIENT_DATABASE_HOST=<public-dns-name>.rds.amazonaws.com
      - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
      - MYSQL_CLIENT_DATABASE_ROOT_USER=admin
      - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=password
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_magento
      - MYSQL_CLIENT_CREATE_DATABASE_USER=dev
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=password
      - MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=ALL
      # MAGENTO WEBAPP PROPS
      - MAGENTO_MODE=developer
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=<public-dns-name>.rds.amazonaws.com
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_DATABASE_USER=dev
      - MAGENTO_DATABASE_PASSWORD=password
      - BITNAMI_DEBUG=true
      # ELASTICSEARCH PROPS
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
 ```
**Queries**
- referring to this doc -- [magento doc to connect to aws](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/mysql_remote.html#connecting-to-an-aws-aurora-database), how can i use this image to link magento container with my aws rds instance.
- in the above compose file, I'm configuring magento to connect with aws rds instance but as can be seen from the logs, it's still trying to connect with 'mariadb'. Could you please explain why it's happening.
- is this image tightly coupled with mariadb ?

**Comment by alemorcuq** [comment]
From the logs:

> magento 12:23:33.10 INFO  ==> Restoring persisted Magento installation

It looks like you are restoring a previous installation, and the persisted Magento config file probably has a different database configured (from the logs it looks like the host is `mariadb`).

**Comment by kd-labs** [comment]
Hi @alemorcuq 

The original compose file from bitnami/magento is like this,
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
```
My intent is to connect the magento service with aws rds instance hence I overriden the magento_database env vars and removed the mariadb service from the compose file.
Could you please guide me as to how I can change the Magento config file or any other thing that allows magento to connect with aws rds instance and creates tables and persists data there rather than look for mariadb.

Thanks

**Comment by alemorcuq** [comment]
I understand you want to start from scratch on the RDS database, right? In that case, the easiest thing to do would be to destroy your volumes (`docker-compose down -v`) and running `docker-compose up` again using the docker-compose file that connects to RDS.

**Comment by Hemp-Blockchain-MSA** [comment]
> > Could you share your logs with the environment variable `BITNAMI_DEBUG=true` set?
> 
> ```shell
> magento 12:23:25.67
> magento 12:23:25.67 Welcome to the Bitnami magento container
> magento 12:23:25.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
> magento 12:23:25.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
> magento 12:23:25.67
> magento 12:23:25.68 INFO  ==> ** Starting Magento setup **
> magento 12:23:25.69 DEBUG ==> Validating settings in APACHE_* environment variables
> realpath: /bitnami/apache/conf: No such file or directory
> magento 12:23:25.73 INFO  ==> Configuring PHP options
> magento 12:23:25.74 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
> magento 12:23:25.75 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
> magento 12:23:25.75 INFO  ==> Trying to connect to the database server
> magento 12:23:25.75 DEBUG ==> Executing SQL command:
> SELECT 1
> 1
> magento 12:23:27.04 INFO  ==> Creating database user dev
> magento 12:23:27.04 DEBUG ==> creating database user \'dev\'
> magento 12:23:27.05 DEBUG ==> Executing SQL command:
> create user if not exists 'dev'@'%' identified by "password";
> magento 12:23:28.36 DEBUG ==> Removing all other hosts for the user
> magento 12:23:28.36 DEBUG ==> Executing SQL command:
> select Host from user where User='dev' and Host!='%';
> magento 12:23:29.84 INFO  ==> Creating database bitnami_magento
> magento 12:23:29.84 DEBUG ==> Creating database bitnami_magento
> magento 12:23:29.85 DEBUG ==> Executing SQL command:
> create database if not exists `bitnami_magento` ;
> magento 12:23:31.45 DEBUG ==> Providing privileges to username dev on database bitnami_magento
> magento 12:23:31.45 DEBUG ==> Executing SQL command:
> grant ALL on `bitnami_magento`.* to 'dev'@'%';
> magento 12:23:33.04 DEBUG ==> Validating settings in MAGENTO_* environment variables...
> magento 12:23:33.05 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
> magento 12:23:33.10 INFO  ==> Restoring persisted Magento installation
> magento 12:23:40.02 INFO  ==> Trying to connect to the database server
> magento 12:23:40.02 DEBUG ==> Getting configuration path '/db/connection/default/dbname' from Magento configuration
> magento 12:23:40.04 DEBUG ==> Getting configuration path '/db/connection/default/username' from Magento configuration
> magento 12:23:40.06 DEBUG ==> Getting configuration path '/db/connection/default/password' from Magento configuration
> magento 12:23:40.08 DEBUG ==> Getting configuration path '/db/connection/default/host' from Magento configuration
> magento 12:23:40.10 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:23:45.17 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:23:50.25 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:23:55.33 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:24:00.40 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:24:05.47 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:24:10.54 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:24:15.61 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:24:20.69 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:24:25.76 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:24:30.83 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:24:35.91 DEBUG ==> Executing SQL command:
> SELECT 1
> ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
> magento 12:24:40.98 ERROR ==> Could not connect to the database
> ```
> 
> The magento service section in compose file is :
> 
> ```yaml
> version: '2'
> services:
>   magento:
>     image: docker.io/bitnami/magento
>     ports:
>       - '80:8080'
>       - '443:8443'
>     environment:
>       # MYSQL CLIENT ENV PROPS
>       - MYSQL_CLIENT_FLAVOR=mysql
>       - MYSQL_CLIENT_DATABASE_HOST=<public-dns-name>.rds.amazonaws.com
>       - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
>       - MYSQL_CLIENT_DATABASE_ROOT_USER=admin
>       - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=password
>       - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_magento
>       - MYSQL_CLIENT_CREATE_DATABASE_USER=dev
>       - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=password
>       - MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=ALL
>       # MAGENTO WEBAPP PROPS
>       - MAGENTO_MODE=developer
>       - MAGENTO_HOST=localhost
>       - MAGENTO_DATABASE_HOST=<public-dns-name>.rds.amazonaws.com
>       - MAGENTO_DATABASE_PORT_NUMBER=3306
>       - MAGENTO_DATABASE_NAME=bitnami_magento
>       - MAGENTO_DATABASE_USER=dev
>       - MAGENTO_DATABASE_PASSWORD=password
>       - BITNAMI_DEBUG=true
>       # ELASTICSEARCH PROPS
>       - ELASTICSEARCH_HOST=elasticsearch
>       - ELASTICSEARCH_PORT_NUMBER=9200
>       # ALLOW_EMPTY_PASSWORD is recommended only for development.
>       - ALLOW_EMPTY_PASSWORD=yes
>     volumes:
>       - 'magento_data:/bitnami/magento'
>     depends_on:
>       - elasticsearch
>   elasticsearch:
>     image: docker.io/bitnami/elasticsearch:7
>     volumes:
>       - 'elasticsearch_data:/bitnami/elasticsearch/data'
> volumes:
>   magento_data:
>     driver: local
>   elasticsearch_data:
>     driver: local
> ```
> 
> **Queries**
> 
> * referring to this doc -- [magento doc to connect to aws](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/mysql_remote.html#connecting-to-an-aws-aurora-database), how can i use this image to link magento container with my aws rds instance.
> * in the above compose file, I'm configuring magento to connect with aws rds instance but as can be seen from the logs, it's still trying to connect with 'mariadb'. Could you please explain why it's happening.
> * is this image tightly coupled with mariadb ?

@alemorcuq  - I want to connect magento with RDS db on aws. As you could see in the above referenced comment, I have overridden MAGENTO_DATABASE_HOST to point to AWS RDS instance but when I'm running docker-compose up with BITNAME_DEBUG=1, we could see in the logs that magento is still trying to connect with mariadb although as per the env variables it should connect to AWS RDS instance.

**Comment by alemorcuq** [comment]
If you want to use an RDS DB why did you first launch Magento with a local MariaDB database? If you don't need anything from that local MariaDB database, just remove the existing volumes and start again with the RDS database and it should work.

**Comment by kd-labs** [comment]
@alemorcuq - Yes, if you refer the below compose file. I'm launching the magento service with AWS RDS instance configured in the env vars and I've also removed mariadb service and mariadb volume. 
When I launch docker-compose using the below compose file and BITNAMI_DEBUG=1 set, we can see in the logs that the magento service is still looking for mariadb service.

```yaml
version: '2'
services:
  magento:
    image: docker.io/bitnami/magento
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      # MYSQL CLIENT ENV PROPS
      - MYSQL_CLIENT_FLAVOR=mysql
      - MYSQL_CLIENT_DATABASE_HOST=<public-dns-name>.rds.amazonaws.com
      - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
      - MYSQL_CLIENT_DATABASE_ROOT_USER=admin
      - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=password
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_magento
      - MYSQL_CLIENT_CREATE_DATABASE_USER=dev
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=password
      - MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=ALL
      # MAGENTO WEBAPP PROPS
      - MAGENTO_MODE=developer
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=<public-dns-name>.rds.amazonaws.com
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_DATABASE_USER=dev
      - MAGENTO_DATABASE_PASSWORD=password
      - BITNAMI_DEBUG=true
      # ELASTICSEARCH PROPS
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
```

Logs after running docker-compose up with above compose file,

```shell
magento 12:23:33.04 DEBUG ==> Validating settings in MAGENTO_* environment variables...
magento 12:23:33.05 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
magento 12:23:33.10 INFO  ==> Restoring persisted Magento installation
magento 12:23:40.02 INFO  ==> Trying to connect to the database server
magento 12:23:40.02 DEBUG ==> Getting configuration path '/db/connection/default/dbname' from Magento configuration
magento 12:23:40.04 DEBUG ==> Getting configuration path '/db/connection/default/username' from Magento configuration
magento 12:23:40.06 DEBUG ==> Getting configuration path '/db/connection/default/password' from Magento configuration
magento 12:23:40.08 DEBUG ==> Getting configuration path '/db/connection/default/host' from Magento configuration
magento 12:23:40.10 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:23:45.17 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:23:50.25 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:23:55.33 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:00.40 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:05.47 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:10.54 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:15.61 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:20.69 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:25.76 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:30.83 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:35.91 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-2)
magento 12:24:40.98 ERROR ==> Could not connect to the database
```
So that is why I've raised this issue, that even after removing mariadb service and volume and configuring magento's environment database properties to point to RDS instance, it's still looking for mariadb service.
