### ISSUE TITLE
Magento container is empty after started

### ISSUE THREAD

**Issue by ahsan-horani-folio** [bitnami/bitnami-docker-magento#231]
I am using following YML file to start containers using bitnami Magento image. I am successfully able to start the containers but however when I try` ls /bitnami/magento` I get empty container. And my container is not accessible via external port http://localhost:82/

Then after some time, I try to list the files inside /bitnami/magento and I am able to see Magento directories. And then the containers is also accessible. That'w quite strange!

As per my observation, there is a cron/scheduler that copies/pulls code at /bitnami/magento directory. This is a bug for me. As I want to start and access my containers as soon as I create them.

Please find docker-compose.yml below

```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    ports:
      - '3307:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:latest
    ports:
      - '82:8080'
      - '445:8443'
    environment:
      - MAGENTO_HOST=localhost:82
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    ports:
      - '9201:9200'
      - '9301:9300'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
```
I observed the same behavior for mariadb container as well. The data is being imported after some time. Not available right after the containers are created. What is the process of getting the image ready as soon as the containers are up?
