### ISSUE TITLE
Mount extensions to app/code without breaking container

### ISSUE THREAD

**Issue by lokhman** [bitnami/bitnami-docker-magento#236]
### Name and Version

bitnamo:magento

### What is the problem this feature will solve?

I wanted to use the `bitnami:magento` image to develop a Magento 2 extension on my local machine.

In `docker-compose.yml` I have added the following volumes specified:
```yaml
services:
    ...
    magento:
        image: docker.io/bitnami/magento:2
        depends_on:
            - mariadb
            - elasticsearch
        environment:
            ...
        volumes:
            - "magento_data:/bitnami/magento"
            - "./src:/bitnami/magento/app/code/MyCompany/MyExtension"
    ...
```

But this setup is failing because the `is_app_initialized` Bash script checks whether the `/app` directory is empty, and based on that decides whether to install Magento from the scratch or not.

(N.B.: I'm not a professional Magento developer and maybe doing it wrong)

### What is the feature you are proposing to solve the problem?

Would it be possible to do the `is_app_initialized` check differently, not based on whether the `app` directory is empty?
