### ISSUE TITLE
PHP Warning:  require(/opt/bitnami/magento/app/etc/env.php): failed to open stream: No such file or directory in Command line code on line 1 PHP Fatal error:  require(): Failed opening required '/opt/bitnami/magento/app/etc/env.php' (include_path='.:/opt/bitnami/php/lib/php') in Command line code on line 1

### ISSUE THREAD

**Issue by aadi008** [bitnami/bitnami-docker-magento#242]
### Name and Version

bitnami/magento:2.4.3

### What steps will reproduce the bug?
```yaml
  magento:
    image: docker.io/bitnami/magento:2.4.3
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=57h7Cx2q
      - MAGENTO_ENABLE_DATABASE_SSL=no
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200

    volumes:
      - 'magento_data:/bitnami/magento'
volumes
  magento_data:
    driver: local
 ```

### What is the expected behavior?

magento container must be created

### What do you see instead?
```
PHP Warning:  require(/opt/bitnami/magento/app/etc/env.php): failed to open stream: No such file or directory in Command line code on line 1
PHP Fatal error:  require(): Failed opening required '/opt/bitnami/magento/app/etc/env.php' (include_path='.:/opt/bitnami/php/lib/php') in Command line code on line 1
```

### Additional information

![image](https://user-images.githubusercontent.com/97296664/160616884-7365db87-439b-47ad-865d-384097411d61.png)
