### ISSUE TITLE
Error when setting volumes

### ISSUE THREAD

**Issue by felek000** [bitnami/bitnami-docker-magento#243]
### Name and Version

bitnami-docker-magento

### What steps will reproduce the bug?

I run magneto local on default config works fine. Also when i change localhost settings. When i want to setup volumes to map them with my local data i get errors and container is not run. 

Complete config:
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - './mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=mage2.local
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MAGENTO_MODE=developer
    volumes:
      - './magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - './elasticsearch_data:/bitnami/elasticsearch/data'
#volumes:
#  mariadb_data:
#    driver: local
#  magento_data:
#    driver: local
#  elasticsearch_data:
#    driver: local

```

### What is the expected behavior?

To see running docker, also files and db mount to my local volumes

### What do you see instead?

On `docker-compose up --build` i get following error.:
```
Starting mage2dokcer_mariadb_1       ... error
Starting mage2dokcer_elasticsearch_1 ...

ERROR: for mage2dokcer_mariadb_1  Cannot start service mariadb: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/07d9568008d696c92ad04825573c2940a858187a30dd0f8a48fb9a0702e0bd7c" to rootfs at "/bitnami/mariadb" caused: mounStarting mage2dokcer_elasticsearch_1 ... done
```

### Additional information

Using windows 11 pro on wsl2. 
I also have few other containers they ruining fine so its not a wsl2 problem.
