### ISSUE TITLE
Setting MAGENTO_HOST breaks site

### ISSUE THREAD

**Issue by timberkeley** [bitnami/bitnami-docker-magento#32]
Hi,

I tried to set the magento host so that the app does not redirect to 127.0.0.1 

docker-compose.yml is:
```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - 3306:3306
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/magento:latest'
    ports:
      - '80:80'
      - '443:443'
    environment:
      - MAGENTO_HOST=10.0.85.184
    volumes:
      - 'magento_data:/bitnami/magento'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```

http://10.0.85.184/ fails.

The reported error is 

```
exception(s):
Exception #0 (Exception): Warning: SessionHandler::read(): Session data file is not created by your uid in /opt/bitnami/magento/htdocs/vendor/magento/framework/Session/SaveHandler/Native.php on line 22
```

[magento_stack_trace.txt](https://github.com/bitnami/bitnami-docker-magento/files/636202/magento_stack_trace.txt)

Any ideas?
