### ISSUE TITLE
Use different Publish Port only works for first/main page

### ISSUE THREAD

**Issue by SamuelUnsw** [bitnami/bitnami-docker-magento#61]
**Description**

**Steps to reproduce the issue:**

1. Use a standard docker-compose.yml which contains ports like: '82:80';
2. Then use: docker-compose -f {filename} up to load both MariaDB and Magento docks;

**Describe the results you received:**

Once finished, I could open http://127.0.0.1:82, but once navigate or open page source, I will see all link still points to http://127.0.0.1 (port 80). I already change core_config_data table record to the new baseURL --- http://127.0.0.1:82/.   (I also did clear the /var/cache folder,)

**Describe the results you expected:**

I think all links in the site should point to port 82 one rather than 80.

I will also paste my yml file below and if there is any way we could set baseURL in MariaDB to use different port or hostname, please let me know.

Basically we try to load different LUMA sites by using different ports from multiple docks.

**Additional information you deem important (e.g. issue happens only occasionally):**

Even using Kitematic to mannually  set published port, after saving while the magento container is still loading, I could see page URL in browser is: http://127.0.0.1:82. However once finished loading, it still tries to point to http://127.0.0.1 which is very confusing. 

Here is the yml file:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: 'bitnami/magento:latest'
    environment:       
      - ENVIRONMENT=Test2
    ports:
      - '82:80' #for Test2
    volumes:
      - 'magento_data:/bitnami/magento'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```

**Comment by SamuelUnsw** [comment]
It seems I used the wrong way to clean the cache after updating core_config_data records. The one I mentioned above doesn't work now. And actually I found after running this it becomes OK: 

**./opt/bitnami/magento/htdocs/bin/magento cache:flush**


So my questions are:

1, I did try to call 'magento cache: clean' first then 'flush'. How come if I do that, I got 'page not available' error??

2, If there any way we could put that new baseURL with port number into yml file before deploying? If every time we need to manually update database and flush the cache, it's a little bit annoying.


Thanks again!

**Comment by sameersbn** [comment]
@SamuelUnsw Hello and apologies for the late response.

Can you try the following
 - change the port field to `82:82`
 - add `APACHE_HTTP_PORT=82` to the magento containers env

The following snippet consists of these changes and is based on the snippet you shared in an earlier comment. Do let us know if this resolves the issue.

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: 'bitnami/magento:latest'
    environment:       
      - ENVIRONMENT=Test2
      - APACHE_HTTP_PORT=82
    ports:
      - '82:82' #for Test2
    volumes:
      - 'magento_data:/bitnami/magento'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```
