### ISSUE TITLE
It does not redirect as our expect when I deployed using kubernetes.yml

### ISSUE THREAD

**Issue by fyery-chen** [bitnami/bitnami-docker-magento#67]
The content of kubernetes.yml is:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    labels:
      io.kompose.service: magento
    name: magento
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    selector:
      io.kompose.service: magento
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: mariadb
    name: mariadb
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: mariadb
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    name: magento
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: magento
      spec:
        containers:
        - image: bitnami/magento:latest
          name: magento
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/magento
            name: magento-magento-data
          - mountPath: /bitnami/apache
            name: magento-apache-data
          - mountPath: /bitnami/php
            name: magento-php-data
        restartPolicy: Always
        env:
        - name: MAGENTO_HOST
           value: 192.168.99.11
        volumes:
        - name: magento-magento-data
          persistentVolumeClaim:
            claimName: magento-magento-data
        - name: magento-apache-data
          persistentVolumeClaim:
            claimName: magento-apache-data
        - name: magento-php-data
          persistentVolumeClaim:
            claimName: magento-php-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: magento-magento-data
    name: magento-magento-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: magento-apache-data
    name: magento-apache-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: magento-php-data
    name: magento-php-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: mariadb
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: mariadb
      spec:
        containers:
        - env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
          image: bitnami/mariadb:latest
          name: mariadb
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/mariadb
            name: magento-mariadb-data
        restartPolicy: Always
        volumes:
        - name: magento-mariadb-data
          persistentVolumeClaim:
            claimName: magento-mariadb-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: magento-mariadb-data
    name: magento-mariadb-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}
```
The NodeIP is `192.168.99.11`, and I set the env MAGENTO_HOST to `192.168.99.11` as well.

Yeah, I use kubernetes.yml to deploy magento, and verify that all pods and svcs are ready and running as shown in the below:

```
magento host$ kubectl get po,svc
NAME                          READY     STATUS    RESTARTS   AGE
po/magento-1324630615-9vhw2   1/1       Running   0          13m
po/mariadb-3904408697-4x90w   1/1       Running   0          10m

NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
svc/kubernetes   10.0.0.1     <none>        443/TCP                      29d
svc/magento      10.0.0.24    <nodes>       80:31490/TCP,443:31521/TCP   1h
svc/mariadb      None         <none>        55555/TCP                    1h
```
Then I access the web server throuth the url `http://192.168.99.11:31490`, but it always redirects to `http://192.168.99.11`.  So I want to know if port `80` or `443` must be exposed to the host and both must be the same, for example, if the listening port of apache is 80, then the host port must be 80 as well, otherwise it will redirect to the port in container. If really like this, then I think maybe it is a bug.
