### ISSUE TITLE
Allow usage of existing database instead of provisioning while installing

### ISSUE THREAD

**Issue by sabbour** [bitnami/bitnami-docker-magento#73]
Similar to how the WordPress scripts work (https://github.com/bitnami/bitnami-docker-wordpress/tree/master/4/rootfs), the Magento setup scripts should allow the usage of an existing database provisioned outside the installer.

This is important for Helm charts that rely on the Service Broker to create the required components. The Service Broker takes care of creating the database server and the actual database on the cloud provider.

See:
https://github.com/Azure/open-service-broker-azure/issues/197
https://github.com/bitnami/bitnami-docker-magento/issues/72
https://github.com/kubernetes/charts/issues/1727

**Comment by juan131** [comment]
I agree with you and a solution similar to the one implemented on WordPress Image to use existing database should be implemented (https://github.com/bitnami/bitnami-docker-wordpress#use-an-existing-database).

This behaviour is currently supported by WordPress, Mediawiki, Phpbb, Ghost and Drupal.

We have an internal task to extend this to other Docker Images (Moodle, Phabricator, Redmine, etc.). I'd add this image to the list.

**Comment by sabbour** [comment]
Is there a way to contribute to this?

**Comment by juan131** [comment]
I am afraid this logic is implemented in the Nami modules of each application (Magento in this case) and the repositories which contains that logic are not public yet. Therefore, it is not possible to contribute to them at this very moment but we would highly recommend you to share with us any concern you may have about them and we will take into account when modifying the Nami modules' logic. Thanks so much for your interest.

**Comment by sabbour** [comment]
Thanks, one concern/quick fix related to the same issue would be this: https://github.com/bitnami/bitnami-docker-magento/issues/72

**Comment by beltran-rubo** [comment]
We are working on this, we plan to have it ready this week.

**Comment by tompizmor** [comment]
Hello @sabbour,

I just want to inform you that we have released a new Magento docker image (`2.2.2-r1` tag) that supports using an existing database. 

Please pull the latest image and check the following docker-compose as an example:

```
$ docker pull bitnami/magento
```

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'bitnami/magento:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
```
