### ISSUE TITLE
Magento is not starting on MiniKube

### ISSUE THREAD

**Issue by jmhanna** [bitnami/bitnami-docker-magento#83]
C:\WINDOWS\system32>kubectl logs -f aspiring-opossum-magento-665855b888-w7nb8
[0m
[0m[1mWelcome to the Bitnami magento container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-magento[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-magento/issues[0m
[0m
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing magento
magento INFO  Preparing PHP environment...
magento INFO  Preparing webserver environment...
magento INFO  Preparing Magento environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at aspiring-opossum-mariadb:3306
mysql-c INFO  MySQL server listening and working at aspiring-opossum-mariadb:3306
magento INFO  Installing Magento...
Error executing 'postInstallation':

  [InvalidArgumentException]
  Parameter validation failed

Exception trace:
 () at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:189
 Magento\Setup\Console\Command\InstallCommand->initialize() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Command/Command.php:207
 Symfony\Component\Console\Command\Command->run() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /opt/bitnami/magento/htdocs/bin/magento:23

setup:install [--backend-frontname BACKEND-FRONTNAME] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user ADMIN-USER] [--admin-password ADMIN-PASSWORD] [--admin-email ADMIN-EMAIL] [--admin-firstname ADMIN-FIRSTNAME] [--admin-lastname ADMIN-LASTNAME] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [-i|--interactive] [--magento-init-params MAGENTO-INIT-PARAMS]

**Comment by juan131** [comment]
Hi @jmhanna 

Could you share the deployment definition (yaml format) you used to deploy Magento? Are you using *helm* to deploy Magento?

**Comment by jmhanna** [comment]
Dear Juan,

thank you for your reply.
Yes, I am using helm to deploy Magento.
I am using the following command:

helm install stable/magento


,
Regards,
Joseph

**Comment by juan131** [comment]
Hi @jmhanna 

When you deploy Magento using helm, you need to indicate a hostname using the `magentoHost` parameter. Any other way, you'll find the error below:

```
NOTES:
###############################################################################
### ERROR: You did not provide an external host in your 'helm install' call ###
###############################################################################
```

For instance, you can use the command below:

```
helm install stable/magento --name magento --set magentoHost=my.custom.host.com
```

You should obtain an output like the one below when you check the logs of the created pod:

```
$ kubectl logs -f magento-magento-XXXXXXXXX

Welcome to the Bitnami magento container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing magento
magento INFO  Preparing PHP environment...
magento INFO  Preparing webserver environment...
magento INFO  Preparing Magento environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at magento-mariadb:3306
mysql-c INFO  MySQL server listening and working at magento-mariadb:3306
magento INFO  Installing Magento...
magento INFO  Deploying to developer mode...
magento INFO  Reindexing...
magento INFO  Flushing cache...
magento INFO  Cleaning up cache folders after installing
```

**Comment by aynurin** [comment]
Hi there,

I have the same issue here. I'm deploying to Azure AKS, and I'm not using helm.

```bash
> kubectl apply -f .\mydefinition.yaml
...
$ kubectl logs my-magento-store-86c67d4f7d-kd4qj
[0m
[0m[1mWelcome to the Bitnami magento container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-magento[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-magento/issues[0m
[0m
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing magento
magento INFO  Preparing PHP environment...
magento INFO  Preparing webserver environment...
magento INFO  Preparing Magento environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at tbhsf-db.mysql.database.azure.com:3306
mysql-c INFO  MySQL server listening and working at tbhsf-db.mysql.database.azure.com:3306
magento INFO  Installing Magento...
Error executing 'postInstallation':
In InstallCommand.php line 264:

  [InvalidArgumentException]
  Parameter validation failed


Exception trace:
 () at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:264
 Magento\Setup\Console\Command\InstallCommand->initialize() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Command/Command.php:221
 Symfony\Component\Console\Command\Command->run() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:893
 Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Console/Cli.php:102
 Magento\Framework\Console\Cli->doRun() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /opt/bitnami/magento/htdocs/bin/magento:23

setup:install [--backend-frontname BACKEND-FRONTNAME] [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--session-save-redis-sentinel-master SESSION-SAVE-REDIS-SENTINEL-MASTER] [--session-save-redis-sentinel-servers SESSION-SAVE-REDIS-SENTINEL-SERVERS] [--session-save-redis-sentinel-verify-master SESSION-SAVE-REDIS-SENTINEL-VERIFY-MASTER] [--session-save-redis-sentinel-connect-retires SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETIRES] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--cache-backend-redis-password CACHE-BACKEND-REDIS-PASSWORD] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--page-cache-redis-password PAGE-CACHE-REDIS-PASSWORD] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user [ADMIN-USER]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--admin-firstname [ADMIN-FIRSTNAME]] [--admin-lastname [ADMIN-LASTNAME]] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [--enable-modules [ENABLE-MODULES]] [--disable-modules [DISABLE-MODULES]] [--convert-old-scripts [CONVERT-OLD-SCRIPTS]] [-i|--interactive] [--safe-mode [SAFE-MODE]] [--data-restore [DATA-RESTORE]] [--dry-run [DRY-RUN]] [--magento-init-params MAGENTO-INIT-PARAMS]
```

Here is my k8s yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-magento-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-magento-store
  template:
    metadata:
      labels:
        app: my-magento-store
    spec:
      containers:
      - name: my-magento-store
        image: bitnami/magento:latest
        resources:
          requests:
            cpu: 800m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 2048Mi
        ports:
        - containerPort: 80
        env: # https://github.com/bitnami/bitnami-docker-magento
        - name: MAGENTO_HOST # Host domain or IP.
          value: mystore.mydomain.com
        - name: MARIADB_HOST # Hostname for MariaDB server. Default: mariadb
          value: mystore-db.mysql.database.azure.com
        - name: MAGENTO_DATABASE_NAME # Database name that Magento will use to connect with the database. Default: bitnami_magento
          value: magento
        - name: MAGENTO_DATABASE_USER # Database user that Magento will use to connect with the database. Default: bn_magento
          value: superuser@mystore-db
        - name: MAGENTO_DATABASE_PASSWORD # Database password that Magento will use to connect with the database. No defaults. Required.
          value: ***
---
apiVersion: v1
kind: Service
metadata:
  name: my-magento-store
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: my-magento-store
```

Thanks!
Shavkat

**Comment by juan131** [comment]
Hi @aynurin 

Could you try using the env. section below?

```yaml
        env:
        - name: MARIADB_HOST
          value: "mystore-db.mysql.database.azure.com"
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: MAGENTO_DATABASE_NAME
          value: "magento"
        - name: MAGENTO_DATABASE_USER
          value: "superuser@mystore-db"
        - name: MAGENTO_DATABASE_PASSWORD
          value: ***
        - name: MAGENTO_HOST
          value: "mystore.mydomain.com"
        - name: MAGENTO_USERNAME
          value: "user"
        - name: MAGENTO_PASSWORD
          value: ***
        - name: MAGENTO_EMAIL
          value: "user@example.com"
        - name: MAGENTO_ADMINURI
          value: "admin"
        - name: MAGENTO_MODE
          value: "developer"
```

**Comment by aynurin** [comment]
Thanks for responding, @juan131 

I get the same error with this section. Is there a chance I can find which parameter it does not like? I've had a look at the source code and it seems that the underlying class does not provide the parameter name it fails with.

```php
    /**
     * @inheritdoc
     */
    protected function initialize(InputInterface $input, OutputInterface $output)
    {
        $inputOptions = $input->getOptions();

        if ($inputOptions['interactive']) {
            $configOptionsToValidate = $this->interactiveQuestions($input, $output);
        } else {
            $configOptionsToValidate = [];
            foreach ($this->configModel->getAvailableOptions() as $option) {
                if (array_key_exists($option->getName(), $inputOptions)) {
                    $configOptionsToValidate[$option->getName()] = $inputOptions[$option->getName()];
                }
            }
        }

        if ($inputOptions['interactive']) {
            $command = '';
            foreach ($configOptionsToValidate as $key => $value) {
                $command .= " --{$key}={$value}";
            }
            $output->writeln("<comment>Try re-running command: php bin/magento setup:install{$command}</comment>");
        }

        $errors = $this->configModel->validate($configOptionsToValidate);
        $errors = array_merge($errors, $this->validateAdmin($input));
        $errors = array_merge($errors, $this->validate($input));
        $errors = array_merge($errors, $this->userConfig->validate($input));

        if (!empty($errors)) {
            foreach ($errors as $error) {
                $output->writeln("<error>$error</error>");
            }
            throw new \InvalidArgumentException('Parameter validation failed');
        }
    }
```

**Comment by juan131** [comment]
Hi @aynurin 

It's a matter of some missing parameter when calling `magento setup:install`...

Could you try adding these two env. variables too?

```yaml
        - name: MAGENTO_FIRSTNAME
          value: "FirstName"
        - name: MAGENTO_LASTNAME
          value: "LastName"
```

**Comment by aynurin** [comment]
Thanks, @juan131, it was a good hint that some parameters were missing. I went through the readme again and found the missing parameters. I didn't specify any parameters relating to creating of the database. I've added the following and it worked. 

There was a small and somewhat obvious catch for Azure MySQL deployment - `MYSQL_CLIENT_CREATE_DATABASE_USER` has to be specified without the hostname specifier, and the `MAGENTO_DATABASE_USER` - with the hostname. So I added the following and it worked:

```yaml

        - name: MYSQL_CLIENT_CREATE_DATABASE_NAME # New database to be created by the mysql client module. No defaults.
          value: "magento"
        - name: MYSQL_CLIENT_CREATE_DATABASE_USER # New database user to be created by the mysql client module. No defaults.
          value: "username" # the username that will be created, without the `@'host'` part
        - name: MYSQL_CLIENT_CREATE_DATABASE_PASSWORD # Database password for the MYSQL_CLIENT_CREATE_DATABASE_USER user. No defaults.
          value: "password" # the password forthe new user
        - name: MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES # Comma-separated list of privileges to grant to the database user. Default: ALL
          value: "ALL"
        - name: ALLOW_EMPTY_PASSWORD # It can be used to allow blank passwords. Default: no
          value: "no"
        - name: MARIADB_ROOT_USER # Database admin user. Default: root
          value: "adminuser@host" # the user that will be used to create the abovementioned user and db
        - name: MARIADB_ROOT_PASSWORD # Database password for the MARIADB_ROOT_USER user. No defaults.
          value: "adminpassword" # the password for the above user
```

Thanks a lot for your help!
