### ISSUE TITLE
Magento instillation stops after Cleaning up cache folders after installing 

### ISSUE THREAD

**Issue by saurabh-parekh** [bitnami/bitnami-docker-magento#84]
I am using your latest docker image to setup magento2 with mariadb. 

I have modified port number to run system on different port. 
It stops processing after 

> magento INFO  Cleaning up cache folders after installing

My `docker-compose.yml` file looks like 
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'bitnami/magento:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
    ports:
      - '8089:80'
      - '4431:443'
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
```
I am running command 

`docker-compose up`

I am getting 500 error on browser. Where can I check error logs?

> http://127.0.0.1:8089/

I am using ubuntu on local system.
