### ISSUE TITLE
Magento doesn't work under a path like `/shop`

### ISSUE THREAD

**Issue by lucasfais** [bitnami/bitnami-docker-magento#97]
**Description**

When you try to configure Magento to work under a url with a path (ex: `my.custom.domain/shop/`), it doesn't work, resulting in a 404 when you access `http://my.custom.domain/shop/`

**Steps to reproduce the issue:**

1. Use the following `dokcer-compose.yml` file:

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'bitnami/magento:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_HOST=my.custom.domain/shop
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local

```

2. Access `http://my.custom.domain/shop/`

**Result**

HTTP Status 404 Not Found:

<img width="708" alt="screen shot 2018-12-11 at 15 08 30" src="https://user-images.githubusercontent.com/26623/49817340-191b4600-fd57-11e8-91cd-f78a296a4e9d.png">
